### ISSUE TITLE
JVM9+ support

### ISSUE THREAD

**Issue by souenzzo** [venantius/pyro#23]
The `javax.xml.bind.DatatypeConverter` is deprecated on JVM9+
https://docs.oracle.com/javase/9/docs/api/java.xml.bind-summary.html

It's a common issue on clj comunity and a example/possible fix:
https://github.com/clojure/clojurescript/commit/544c1b77d76d48f234cdb03746ea993158c46aff

original issue:
https://gist.github.com/bhb/2686b023d074ac052dbc21f12f324f18#gistcomment-2641982

**Comment by souenzzo** [comment]
Waiting for pyro 0.1.3 ;)

**Comment by ghadishayban** [comment]
Consider moving to JDK8+ only, and using java.util.Base64. (That's what Clojure itself is doing in 1.10 https://github.com/clojure/clojure/blob/master/test/clojure/test_clojure/java_interop.clj#L196-L198)

**Comment by venantius** [comment]
I'd be happy to take a PR on that - seems like it'd be a lot cleaner than the current implementation.

**Comment by madis** [comment]
I'm also waiting for the next release. Until that, for Lein projects you can use the following in `project.clj` to pull the source directly from github:

```clojure
  ; Allow clojure sources from git repositories
  :plugins [[reifyhealth/lein-git-down "0.3.6"]]
  :middleware [lein-git-down.plugin/inject-properties]
  :repositories [["public-github" {:url "git://github.com"}]]
  :git-down {pyro {:coordinates venantius/pyro}}
  :dependencies [[venantius/pyro "8f71aa054f7d54d38be090c3a78b4843e4e6b0ca"]]
```

And then in your code:
```clojure
(require '[pyro.printer :as printer])
(printer/swap-stacktrace-engine!)
```
Using clojure `"1.10.1"` with `openjdk version "12.0.1" 2019-04-16`

Gives me nice
```
Testing battleships.core-test

Testing battleships.game-db-test

ERROR in (start-new-game-test) (AFn.java:429)
Uncaught exception, not in assertion.
expected: nil
  actual: clojure.lang.ArityException: Wrong number of args (3) passed to: battleships.game-db/new-game
 at battleships.game-db-test/fn (game_db_test.clj:18)
    16     (testing "creating new game"
    17       (let [db (atom {})
--> 18             new-game-id (db/new-game "fake" :db db)]
    19         (is (db/get-game new-game-id db) "fake"))))

    battleships.game-db-test/fn (game_db_test.clj:15)
    13      :ns-whitelist #"battleships.*"})
    14
--> 15    (deftest start-new-game-test
    16     (testing "creating new game"
    17       (let [db (atom {})
```
